name: Deploy Infrastructure

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
                enable-AzPSSession: true

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Azure CLI
              uses: azure/login@v1

            - name: Deploy infrastructure
              run: |
                    az group create --name myResourceGroup --location northeurope
                    az deployment group create --resource-group myResourceGroup --template-file InfrastructureAsCode/main.bicep
