name: Deploy Infrastructure

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Azure CLI
                uses: azure/login@v1

            - name: Deploy infrastructure
                run: |
                    az group create --name myResourceGroup --location northeurope
                    az deployment group create --resource-group myResourceGroup --template-file InfrastructureAsCode/main.bicep
