name: .NET Workflow

on:
    push:
        paths:
            - 'Application/**'
    pull_request:
        paths:
            - 'Application/**'

env:
    registryName: t66cj4oiyvf44mpnpreg.azurecr.io
    repositoryName: t66cj4oiyvf44mpnpreg/dotnetcoreapp
    dockerFolderPath: Application/src/RazorPagesTestSample/RazorPagesTestSample
    tag: ${{ github.run_number }}

permissions:
    id-token: write # This is required for requesting the JWT

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x

            - name: Restore dependencies
              run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

            - name: Build application
              run: dotnet build Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

            - name: Run tests
              run: dotnet test Application/test/Application.Tests/RazorPagesTestSample.Tests.csproj

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Docker login
              run: docker login ${{ env.registryName }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

            - name: Docker build
              run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} --build-arg build_version=${{ env.tag }} ${{ env.dockerFolderPath }}

            - name: Docker push
              run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

    deploy-test:
        needs: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: OIDC Login to Azure Public Cloud with a PS Session
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
                enable-AzPSSession: true

            - name: Deploy to test environment
              uses: Azure/webapps-deploy@v2
              with:
                app-name: t66cj4oiyvf44-dev
                images: registryName.azurecr.io/t66cj4oiyvf44mpnpreg/dotnetcoreapp:${{ env.tag }}
                slot-name: test
                action: 'Swap'
                resource-group: myResourceGroup

    deploy-prod:
        needs: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Azure login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to prod environment
              uses: Azure/webapps-deploy@v2
              with:
                app-name: prod-webapp
                images: registryName.azurecr.io/t66cj4oiyvf44mpnpreg/dotnetcoreapp:${{ env.tag }}
                slot-name: prod
                action: 'Swap'
                resource-group: prod-resource-group

    manual-approval-test:
        needs: deploy-test
        runs-on: ubuntu-latest

        steps:
            - name: Manual approval
              uses: azure/appservice-manual-approval@v1
              with:
                app-name: t66cj4oiyvf44-dev
                slot-name: test
                resource-group: myResourceGroup

    manual-approval-prod:
        needs: deploy-prod
        runs-on: ubuntu-latest

        steps:
            - name: Manual approval
              uses: azure/appservice-manual-approval@v1
              with:
                app-name: prod-webapp
                slot-name: prod
                resource-group: prod-resource-group
